services:

  Streamline:
    hostname: Streamline
    container_name: Streamline
    image: streamline:latest
    build:
      context: ./docker
      dockerfile: Streamline/streamline.dockerfile
    privileged: true
    volumes:
      - ./volumes/Streamline:/Streamline
      - /dev:/dev
      - /run/udev:/run/udev:ro
    tty: true
    init: true
    stdin_open: true
    network_mode: host

  Streamline_FE:
    hostname: Streamline_FE
    container_name: Streamline_FE
    image: streamline_fe:latest
    build:
      context: ./docker
      dockerfile: Frontend/apache.dockerfile
    volumes:
      - ./volumes/Frontend:/var/www/html:ro
    tty: true
    stdin_open: true
    extra_hosts:
      - "Streamline_FE:127.0.1.1"
    network_mode: host